wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.34
    code_path: code/text_classification/train.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 64
binary:
  desc: null
  value: false
char_level:
  desc: null
  value: false
cuda:
  desc: null
  value: false
data_size:
  desc: null
  value: 1.0
data_url:
  desc: null
  value: https://raw.githubusercontent.com/saams4u/mwml-httynn-app/master/datasets/yelp_labelled.txt
dropout_p:
  desc: null
  value: 0.2
embedding_dim:
  desc: null
  value: 100
filter_sizes:
  desc: null
  value:
  - 2
  - 3
  - 4
filters:
  desc: null
  value: '[!\"''#$%&()*\+,-./:;<=>?@\\\[\]^_`{|}~]'
freeze_embeddings:
  desc: null
  value: false
hidden_dim:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0001
lower:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 100
num_filters:
  desc: null
  value: 50
patience:
  desc: null
  value: 3
seed:
  desc: null
  value: 1234
shuffle:
  desc: null
  value: true
test_size:
  desc: null
  value: 0.15
train_size:
  desc: null
  value: 0.7
use_glove:
  desc: null
  value: true
val_size:
  desc: null
  value: 0.15
